Repository SwEnt-2024-Group-19/Activities, pull requests merged in 2024-11, with the labels that each got.

#109 Add Comment Functionality to Activities with UI and Repository Updates
  app/src/androidTest/java/com/android/sample/ui/activityDetails/ActivityDetailsScreenTest1.kt
  app/src/main/java/com/android/sample/model/activity/ActivitiesRepositoryFirestore.kt
  app/src/main/java/com/android/sample/model/activity/Activity.kt
  app/src/main/java/com/android/sample/ui/activity/CreateActivity.kt
  app/src/main/java/com/android/sample/ui/activity/EditActivity.kt
  app/src/main/java/com/android/sample/ui/activitydetails/ActivityDetailsScreen.kt
Labels: enhancement

#141 Fix Intermittent Failure in `createButton_isDisabledInitially` Test by Ensuring UI Readiness
  app/src/androidTest/java/com/android/sample/ui/activity/CreateActivityScreenTest.kt
Labels: bug

#138 Implement Comment and Reply Management with Deletion Functionality, Tests, and UI Enhancements
  app/src/androidTest/java/com/android/sample/ui/activityDetails/ActivityDetailsScreenTest1.kt
  app/src/androidTest/java/com/android/sample/ui/activityDetails/CommentItemTest.kt
  app/src/main/java/com/android/sample/ui/activitydetails/ActivityDetailsScreen.kt
Labels: enhancement

#144 Implement Single-Level Reply Functionality for Comments
  app/src/androidTest/java/com/android/sample/ui/activityDetails/CommentItemTest.kt
  app/src/main/java/com/android/sample/ui/activitydetails/ActivityDetailsScreen.kt
Labels: enhancement

#147 Update SonarQube Configuration to Prioritize Line Coverage
  app/build.gradle.kts
Labels: refactor

#152 Add user location feature in the map
  app/build.gradle.kts
  app/src/androidTest/java/com/android/sample/ui/activity/CreateActivityScreenTest.kt
  app/src/androidTest/java/com/android/sample/ui/activity/EditActivityScreenTest.kt
  app/src/androidTest/java/com/android/sample/ui/map/MapScreenTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/di/module/RepositoryModule.kt
  app/src/main/java/com/android/sample/model/map/LocationPermissionChecker.kt
  app/src/main/java/com/android/sample/model/map/LocationRepository.kt
  app/src/main/java/com/android/sample/model/map/LocationViewModel.kt
  app/src/main/java/com/android/sample/model/map/NominatimLocationRepository.kt
  app/src/main/java/com/android/sample/ui/map/Map.kt
  app/src/test/java/com/android/sample/model/map/LocationViewModelTest.kt
  app/src/test/java/com/android/sample/model/map/NominatimLocationRepositoryTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#158 Fix (profile creation): no profile creation without name and surname
  app/src/androidTest/java/com/android/sample/ui/profile/ProfileCreationTest.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/authentication/SignIn.kt
  app/src/main/java/com/android/sample/ui/components/Textfields.kt
  app/src/main/java/com/android/sample/ui/profile/ProfileCreation.kt
Labels: bug

#168 Refactor authentication classes
  app/src/androidTest/java/com/android/sample/ui/authentication/SignInScreenTest.kt
  app/src/androidTest/java/com/android/sample/ui/authentication/SignUpScreenTest.kt
  app/src/androidTest/java/com/android/sample/ui/authentication/TextFieldsTest.kt
  app/src/main/java/com/android/sample/ui/authentication/SignIn.kt
  app/src/main/java/com/android/sample/ui/authentication/SignUp.kt
  app/src/main/java/com/android/sample/ui/components/Textfields.kt
Labels: bug, refactor

#171 fix: interests not being updated when creating a profile
  app/src/main/java/com/android/sample/ui/profile/ProfileCreation.kt
Labels: bug

#178 Fix: switch the two buttons to switch account and to continue with logged account
  app/src/main/java/com/android/sample/ui/authentication/ChooseAccount.kt
Labels: refactor

#182 Initial End-to-End Testing Framework & Dependency Injection
  app/src/androidTest/java/com/android/sample/di/module/TestFirebaseModule.kt
  app/src/androidTest/java/com/android/sample/di/module/TestRepositoryModule.kt
  app/src/androidTest/java/com/android/sample/ui/endtoend/ActivityFlowTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/di/module/RepositoryModule.kt
  app/src/main/java/com/android/sample/model/activity/MockActivitiesRepository.kt
  app/src/main/java/com/android/sample/model/map/LocationPermissionChecker.kt
  app/src/main/java/com/android/sample/model/map/LocationViewModel.kt
  app/src/main/java/com/android/sample/model/map/MockLocationPermissionChecker.kt
  app/src/main/java/com/android/sample/model/map/PermissionChecker.kt
  app/src/main/java/com/android/sample/model/profile/MockProfilesRepository.kt
  app/src/main/java/com/android/sample/ui/authentication/SignIn.kt
Labels: testing

#192 Fix map permission not appearing when launching the app
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/ui/map/Map.kt
Labels: bug

#195 Fix/activity creation in guest mode
  app/src/androidTest/java/com/android/sample/ui/endtoend/ActivityFlowTest.kt
Labels: bug

#211 fix: change ui layout of comment reply button
  app/src/main/java/com/android/sample/ui/activitydetails/ActivityDetailsScreen.kt
Labels: bug

#231 Add Distance Calculation and Display Features
  app/src/androidTest/java/com/android/sample/ui/activityDetails/ActivityDetailsScreenTest1.kt
  app/src/androidTest/java/com/android/sample/ui/listActivities/ListActivitiesTest.kt
  app/src/main/java/com/android/sample/MainActivity.kt
  app/src/main/java/com/android/sample/model/map/LocationViewModel.kt
  app/src/main/java/com/android/sample/ui/activitydetails/ActivityDetailsScreen.kt
  app/src/main/java/com/android/sample/ui/listActivities/ViewListActivities.kt
  app/src/test/java/com/android/sample/model/map/LocationViewModelTest.kt
Labels: enhancement

#237 Enhance Activity Scoring and Sorting Functionality
  app/src/androidTest/java/com/android/sample/ui/activity/LikedActivitiesTest.kt
  app/src/androidTest/java/com/android/sample/ui/activityDetails/ActivityDetailsScreenTest1.kt
  app/src/androidTest/java/com/android/sample/ui/listActivities/ListActivitiesTest.kt
  app/src/androidTest/java/com/android/sample/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/android/sample/ui/profile/ProfileScreenTests.kt
  app/src/main/java/com/android/sample/model/activity/ListActivitiesViewModel.kt
  app/src/main/java/com/android/sample/ui/listActivities/ViewListActivities.kt
  app/src/test/java/com/android/sample/model/activities/ListActivitiesViewModelTest.kt
  app/src/test/java/com/android/sample/model/activities/ScoreCalculatorTest.kt
Labels: enhancement

#243 Disable button/database interactions when user is not connected to the network
  app/src/main/java/com/android/sample/ui/activitydetails/ActivityDetailsScreen.kt
  app/src/main/java/com/android/sample/ui/authentication/SignIn.kt
  app/src/main/java/com/android/sample/ui/profile/EditProfile.kt
  app/src/main/java/com/android/sample/ui/profile/Profile.kt
Labels: enhancement, refactor
