Repository SwEnt-2024-Group-19/Activities, pull requests merged in 2024-12, with the labels that each got.

#319 Feature/already enrolled remaining time
  app/src/androidTest/java/com/android/sample/ui/profile/ProfileScreenTests.kt
  app/src/main/java/com/android/sample/ui/profile/Profile.kt
Labels: bug

#297 Fix/nominatim suggestions unfocus keyboard
  app/src/main/java/com/android/sample/ui/activity/CreateActivity.kt
  app/src/main/java/com/android/sample/ui/activity/EditActivity.kt
Labels: bug

#346 fix: remove duplicated code
  app/src/main/java/com/android/sample/ui/activity/CreateActivity.kt
Labels: bug

#334 Feature: Align Categories and Add Subcategories
  app/src/androidTest/java/com/android/sample/model/activity/MockActivitiesRepository.kt
  app/src/androidTest/java/com/android/sample/model/profile/MockProfilesRepository.kt
  app/src/androidTest/java/com/android/sample/ui/endtoend/ActivityFlowTest.kt
  app/src/androidTest/java/com/android/sample/ui/listActivities/ListActivitiesTest.kt
  app/src/androidTest/java/com/android/sample/ui/profile/EditProfileTest.kt
  app/src/androidTest/java/com/android/sample/ui/profile/ParticipantProfileScreenTest.kt
  app/src/androidTest/java/com/android/sample/ui/profile/ProfileCreationTest.kt
  app/src/androidTest/java/com/android/sample/ui/profile/ProfileScreenTests.kt
  app/src/main/java/com/android/sample/model/activity/ActivitiesRepositoryFirestore.kt
  app/src/main/java/com/android/sample/model/activity/Activity.kt
  app/src/main/java/com/android/sample/model/activity/database/Converters.kt
  app/src/main/java/com/android/sample/model/profile/ProfilesRepositoryFirestore.kt
  app/src/main/java/com/android/sample/model/profile/User.kt
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/resources/dummydata/DummyData.kt
  app/src/main/java/com/android/sample/ui/activity/CreateActivity.kt
  app/src/main/java/com/android/sample/ui/activity/EditActivity.kt
  app/src/main/java/com/android/sample/ui/profile/EditProfile.kt
  app/src/main/java/com/android/sample/ui/profile/ParticipantProfile.kt
  app/src/main/java/com/android/sample/ui/profile/Profile.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/profile/ProfilesRepositoryFirestoreTest.kt
Labels: enhancement

#413 UI/navigation/refactor bottom bar
  app/src/main/java/com/android/sample/resources/C.kt
  app/src/main/java/com/android/sample/ui/components/PlusButtonToCreate.kt
  app/src/main/java/com/android/sample/ui/listActivities/LikedActivities.kt
  app/src/main/java/com/android/sample/ui/listActivities/ViewListActivities.kt
  app/src/main/java/com/android/sample/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/sample/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/sample/ui/profile/Profile.kt
Labels: enhancement

#201 Testing/endtoend : Now supports sign in flows
  app/src/androidTest/java/com/android/sample/di/module/TestRepositoryModule.kt
  app/src/androidTest/java/com/android/sample/mockDatabase/MockDatabase.kt
  app/src/androidTest/java/com/android/sample/model/activity/MockActivitiesRepository.kt
  app/src/androidTest/java/com/android/sample/model/authentication/MockSignInRepository.kt
  app/src/androidTest/java/com/android/sample/model/profile/MockProfilesRepository.kt
  app/src/androidTest/java/com/android/sample/ui/activity/LikedActivitiesTest.kt
  app/src/androidTest/java/com/android/sample/ui/activityDetails/ActivityDetailsScreenTest1.kt
  app/src/androidTest/java/com/android/sample/ui/authentication/SignUpScreenTest.kt
  app/src/androidTest/java/com/android/sample/ui/endtoend/ActivityFlowTest.kt
  app/src/androidTest/java/com/android/sample/ui/endtoend/ComposeTestHelper.kt
  app/src/androidTest/java/com/android/sample/ui/endtoend/TestTags.kt
  app/src/androidTest/java/com/android/sample/ui/listActivities/ListActivitiesTest.kt
  app/src/androidTest/java/com/android/sample/ui/profile/ProfileCreationTest.kt
  app/src/main/java/com/android/sample/model/auth/SignInRepository.kt
  app/src/main/java/com/android/sample/model/auth/SignInRepositoryFirebase.kt
  app/src/main/java/com/android/sample/model/profile/ProfileViewModel.kt
  app/src/main/java/com/android/sample/resources/dummydata/E2E_DummyData.kt
  app/src/main/java/com/android/sample/ui/listActivities/ViewListActivities.kt
  app/src/main/java/com/android/sample/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/sample/ui/profile/Profile.kt
  app/src/test/java/com/android/sample/model/profile/ProfileViewModelTest.kt
Labels: testing

#333 Feature: Export Activities to Calendar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/sample/model/activity/ListActivitiesViewModel.kt
  app/src/main/java/com/android/sample/ui/activitydetails/ActivityDetailsScreen.kt
  app/src/main/java/com/android/sample/ui/activitydetails/ExportToCalendarButton.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/sample/model/activities/ListActivitiesViewModel_ExportCalendarTest.kt
Labels: enhancement
